apiVersion: batch/v1
kind: Job
metadata:
  name: icp-mongodb-backup
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: icp-mongodb-backup
        image: hyc-cloud-private-stable-docker-local.artifactory.swg-devops.com/ibmcom-amd64/icp-mongodb
        command: ["bash", "-c", "cat /cred/mongo-certs/tls.crt /cred/mongo-certs/tls.key > /mongo.pem; cat /cred/cluster-ca/tls.crt /cred/cluster-ca/tls.key > /ca.pem; mongodump --oplog --out /dump --host mongodb:$MONGODB_SERVICE_PORT --username $ADMIN_USER --password $ADMIN_PASSWORD --authenticationDatabase admin --ssl --sslCAFile /ca.pem --sslPEMKeyFile /mongo.pem"]
        volumeMounts:
        - mountPath: "/dump"
          name: mongodump
        - mountPath: "/cred/mongo-certs"
          name: icp-mongodb-client-cert
        - mountPath: "/cred/cluster-ca"
          name: cluster-ca-cert
        env:
          - name: ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: icp-mongodb-admin
                key: user
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: icp-mongodb-admin
                key: password
      volumes:
      - name: mongodump
        persistentVolumeClaim:
          claimName: my-mongodump
      - name: icp-mongodb-client-cert
        secret:
          defaultMode: 0400
          secretName: icp-mongodb-client-cert
      - name: cluster-ca-cert
        secret:
          defaultMode: 400
          secretName: cluster-ca-cert
      restartPolicy: Never
