apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-mongodump
  namespace: kube-system
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/nfs/mongodump
    server: 10.10.25.43
