apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-mongodump
  namespace: kube-system
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: <mounted directory>
    server: <nfs server ip address>
